### ISSUE TITLE
# of workers

### ISSUE THREAD

**Issue by inkyusa** [UoA-CARES/essential-gpu-docker#8]
I encountered the following error while running a pytorch code with worker = 12.
```
xception has occurred: RuntimeError
DataLoader worker (pid(s) 4648) exited unexpectedly
RuntimeError: DataLoader worker (pid 4648) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

The above exception was the direct cause of the following exception:

  File "/workspace/GISLR-torch/run_train_fold0.py", line 289, in run_train
    for t, batch in enumerate(train_loader):
  File "/workspace/GISLR-torch/run_train_fold0.py", line 372, in <module>
    run_train()
RuntimeError: DataLoader worker (pid(s) 4648) exited unexpectedly
```
and terminal log

```
RuntimeError: unable to write to file </torch_4655_434291219_38>: No space left on device (28)
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_4753_3315859216_32>: No space left on device (28)
```

When I change `worker = 1`, it runs.

**Comment by jlim262** [comment]
Can you post your disk usage of the container?

**Comment by inkyusa** [comment]
```
root@f01317d6c8db:/workspace/GISLR-torch# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         1.8T  432G  1.3T  25% /
tmpfs            64M     0   64M   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sda1       1.9T  1.4T  455G  76% /input
/dev/sdc3       1.8T  432G  1.3T  25% /workspace
tmpfs            32G   12K   32G   1% /proc/driver/nvidia
tmpfs           6.3G  2.6M  6.3G   1% /run/nvidia-persistenced/socket
udev             32G     0   32G   0% /dev/nvidia0
```

**Comment by jlim262** [comment]
And can you add '-v /dev/shm:/dev/shm ' option when you run your image, and try it again?

**Comment by inkyusa** [comment]
It works with the change. This is what I used for launching docker 
```
docker run -it \             INT  conda_asl py  08:24:03 
    --privileged \
    --gpus all \
    --runtime=nvidia \
    --device=/dev/dri:/dev/dri \
    -e NVIDIA_VISIBLE_DEVICES=all \
    -e NVIDIA_DRIVER_COMPABILITIES=all \
    -e QT_X11_NO_MITSHM=1 \
    -e DISPLAY=$DISPLAY \
    -v "/tmp/.X11-unix/:/tmp/.X11-unix" \
    -v "$HOME/workspace:/workspace" \
    -v /dev/shm:/dev/shm \
    mycares/kaggle-gpu-python:latest \
    /bin/bash
```
